[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-economy"
version = "0.1.0"

[project.entry-points."endstone"]
economy = "endstone_economy:Economy"
